select ROUTENAME 线路名称,
       ROUTETYPENAME 线路类别,
       D2.UNINAME,
       NUM2.UNINAME 所属单位,
       VALUE 线路车辆类型
from G_ROUTENUM,
     G_ROUTETYPE,
          G_UNITNUM D1 JOIN G_UNITNUM D2
         ON D1.PARENTNUM = D2.UNITNUM and D2.PARENTNUM = '00',
     G_UNITNUM NUM1 JOIN G_UNITNUM NUM2
         ON NUM1.PARENTNUM = NUM2.UNITNUM and NUM2.PARENTNUM != '00' and NUM2.PARENTNUM != '00000000',
     G_DICINFO
where
      G_ROUTETYPE.ROUTETYPE = G_ROUTENUM.ROUTETYPE
  and G_DICINFO.DICNAME = 'ROUTEBUSTYPE'
  and G_DICINFO.CODE = G_ROUTENUM.ROUTETYPE
;